// Динамическая генерация robots.txt
export default defineEventHandler(event => {
  //
  const config = useRuntimeConfig(event)
  const isProduction = config.public.PROD_MODE

  // Формируем содержимое robots.txt
  const lines = ['# Generated by Nuxt server route', '', 'User-agent: *']

  // Для не-production сборок - запрещаем всё
  if (!isProduction) {
    lines.push('Disallow: /', '# Non-production build - indexing disabled')
  } else {
    // Для production
    lines.push(
      'Disallow: /admin',
      'Disallow: /search',
      'Disallow: /user',
      'Disallow: /cart',
      'Disallow: /try',
      'Disallow: /test',
      'Disallow: /catalog/*?f=*',
    )
    // Добавляем ссылку на sitemap
    lines.push('', '# Sitemap', 'Sitemap: https://chelinstrument.ru/sitemap.xml')
  }

  // Устанавливаем правильный Content-Type для текстового файла
  setHeader(event, 'Content-Type', 'text/plain; charset=utf-8')

  return lines.join('\n')
})
